export const FILIERES = [
  'L1 Informatique',
  'L2 Informatique',
  'L3 Informatique',
  'L1 Électronique',
  'L2 Électronique',
  'L3 Électronique',
  'L1 Télécommunications',
  'L2 Télécommunications',
  'L3 Télécommunications',
  'L1 Automatique',
  'L2 Automatique',
  'L3 Automatique',
  'M1 Informatique',
  'M2 Informatique',
  'M1 Réseaux & Télécommunications',
  'M2 Réseaux & Télécommunications',
  'M1 Systèmes embarqués',
  'M2 Systèmes embarqués',
];
